//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.Growth.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mPhasingEntities1 : DbContext
    {
        public mPhasingEntities1()
            : base("name=mPhasingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ContactPoint> ContactPoints { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<MediaChannelPlan> MediaChannelPlans { get; set; }
    }
}
