//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimiser.Media.Growth.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactPoint()
        {
            this.MediaChannelPlans = new HashSet<MediaChannelPlan>();
        }
    
        public int ContactPointId { get; set; }
        public string ContactPointName { get; set; }
        public Nullable<int> fkChannelId { get; set; }
    
        public virtual Channel Channel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaChannelPlan> MediaChannelPlans { get; set; }
    }
}
