//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimiser.Media.Growth.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int DivisionId { get; set; }
        public string Division1 { get; set; }
    }
}
