//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.Growth.OptimiserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.ContactPoints = new HashSet<ContactPoint>();
        }
    
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
    
        public virtual ICollection<ContactPoint> ContactPoints { get; set; }
    }
}
