//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media.Growth.OptimiserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPoint
    {
        public ContactPoint()
        {
            this.MediaChannelPlans = new HashSet<MediaChannelPlan>();
        }
    
        public int ContactPointId { get; set; }
        public string ContactPointName { get; set; }
        public Nullable<int> ChannelName { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual ICollection<MediaChannelPlan> MediaChannelPlans { get; set; }
    }
}
